postgre_url: "postgresql://postgres:1@localhost:5432/microcbt"
listen_host: 0.0.0.0
listen_port: 8080
logger:
  format: "%d_%m_%Y"
  path: "logs"
jwt_secret: Hello World
auth:
  limit: 3
  tolerance_different: 2
  block_different_device: true
  block_different_useragent: true